brew "mas"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "fzf"
brew "gh"
brew "git"
brew "git-flow"
brew "mysql", restart_service: true
brew "node"
brew "pure"
brew "redis"
brew "watchman"
brew "yarn"
brew "zsh-completions"
brew "tree"
cask "android-studio"
cask "expo-xde"
cask "gitkraken"
cask "iterm2"
cask "mysqlworkbench"
cask "ngrok"
cask "postman"
cask "spectacle"
cask "visual-studio-code"
cask "webstorm"
mas "Amphetamine", id: 937984704
mas "Tadama", id: 1415817706
